services:
  - type: web
    name: shopify-cart-builder
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
